# Generated by Django 4.2.4 on 2023-08-30 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendance_child_teacher_rename_user_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 1, 57, 45, 897135, tzinfo=datetime.timezone.utc)),
        ),
    ]
