# Generated by Django 4.2.4 on 2023-08-30 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 2, 8, 51, 718144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 8, 30)),
        ),
    ]
