# Generated by Django 4.2.4 on 2023-08-30 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_attendance_datetime_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 5, 51, 21, 851434, tzinfo=datetime.timezone.utc)),
        ),
    ]
