# Generated by Django 4.2.4 on 2023-08-30 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance_reason_alter_attendance_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='child',
            new_name='child_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 8, 42, 36, 234053, tzinfo=datetime.timezone.utc)),
        ),
    ]
