# Generated by Django 4.2.4 on 2023-08-31 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_child_attendance_child_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='child_id',
            new_name='child',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 8, 31)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 57, 5, 323591, tzinfo=datetime.timezone.utc)),
        ),
    ]
