# Generated by Django 4.2.4 on 2023-08-31 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_child_id_attendance_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 1, 20, 4, 353491, tzinfo=datetime.timezone.utc)),
        ),
    ]
