# Generated by Django 4.2.4 on 2023-08-31 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_attendance_date_alter_attendance_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reply',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 2, 41, 30, 159301, tzinfo=datetime.timezone.utc)),
        ),
    ]
